config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users
  resources :contacts
  resources :import_contacts do
    collection { post :import }  
  end
  resources :rejected_contacts, only: [:index]
  root "home#index"
  
end

app/models/import_contact.rb
class ImportContact < ApplicationRecord
  include AASM
  
  default_scope {order("created_at DESC")}
  belongs_to :user
  validates_presence_of :filename, :state

  aasm column: 'state' do
    state :waiting, initial: true
    state :processing, :failed, :finished

    event :processing_file do
      transitions from: :waiting, to: :processing
    end

    event :finished_import do
      transitions from: :processing, to: :finished
    end

    event :failed_import do
      transitions from: :processing, to: :failed
    end
  end

    

  def import_csv(file, user, remote_headers)
    CSV.foreach(file, headers: true) do |row|
      contact_hash = row.to_hash
      contact = Contact.new(name: contact_hash['name'], 
                            birthday: contact_hash['birthday'], 
                            phone: contact_hash['phone'], 
                            address: contact_hash['address'], 
                            credit_card: contact_hash['credit_card'],
                            last_digits: contact_hash['credit_card'],
                            franchise: contact_hash['credit_card'], 
                            email: contact_hash['email'],
                            user_id: user.id)
      contact.assign_attributes(Contact.headers_pair(user, contact_hash, remote_headers))  
      processing_file! if may_processing_file?
      if contact.save && may_finished_import?
        finished_import!
      else
        reject_contacts!(user, contact, contact_hash, remote_headers)
 
      end
    end
  end

  def reject_contacts!(user, contact, contact_hash, remote_headers)
    errors = []
    errors = contact.errors.full_messages.join(', ')
    rejected_contact = RejectedContact.new(name: contact_hash['name'], 
                                          birthday: contact_hash['birthday'], 
                                          phone: contact_hash['phone'], 
                                          address: contact_hash['address'], 
                                          credit_card: contact_hash['credit_card'],
                                          last_digits: contact_hash['credit_card'],
                                          franchise: contact_hash['credit_card'], 
                                          email: contact_hash['email'],
                                          user_id: user.id)
    rejected_contact.assign_attributes(Contact.headers_pair(user, contact_hash, remote_headers))               
    rejected_contact.error = errors                                      
    processing_file! if may_processing_file?
    rejected_contact.save!
    failed_import! if may_failed_import?
  end

  
end

app/controllers/import_contacts_controller.rb
class ImportContactsController < ApplicationController
  before_action :authenticate_user!

  def new
    @import_contacts = ImportContact.new
    @import_contact = ImportContact.all
  end

  def index
    @imported_contacts = ImportContact.all.paginate(page: params[:page], per_page: 10)
  end
  
  def import
    file_path = '/tmp/contacts.csv'
    File.binwrite(file_path, params[:file].read)
    remote_headers = params.to_unsafe_hash.select { |key,value| key.match(/name|birthday|phone|address|credit_card|email/) }
    ContactsImporterJob.perform_later(file_path, current_user.id, params[:file].original_filename, remote_headers)
    redirect_to contacts_path, alert: 'Contacts imported.'
  end

end

app/helpers/import_contacts_helper.rb
module ImportContactsHelper
end

app/views/import_contacts/_form.html.erb
<%= form_tag import_import_contacts_path, multipart: true do %>
  <div>
  <%= file_field_tag :file, required: true %>
  </div>
  <div>
    <%= 'Select your 1st row'%>
    <%= select_tag "name", options_for_select([ "name", "birthday", "phone", "address", "credit_card", "email" ], "name"), :required => true %>
    <%= label_tag 'or your own field'%>
    <%= text_field_tag :name, '', :required => false %>
  </div>
  <div>
  <%= 'Select your 2nd row'%>
    <%= select_tag "birthday", options_for_select([ "name", "birthday", "phone", "address", "credit_card", "email" ], "birthday"), :required => true %>
  <%= label_tag 'or your own field'%>
    <%= text_field_tag :birthday, '', :required => false %>
  </div>
  <div>
  <%= 'Select your 3rd row'%>
    <%= select_tag "phone", options_for_select([ "name", "birthday", "phone", "address", "credit_card", "email" ], "phone"), :required => true %>
  <%= label_tag 'or your own field'%>
    <%= text_field_tag :phone, '', :required => false %>
  </div>
  <div>
  <%= 'Select your 4th row'%>
    <%= select_tag "address", options_for_select([ "name", "birthday", "phone", "address", "credit_card", "email" ], "address"), :required => true %>
  <%= label_tag 'or your own field'%>
    <%= text_field_tag :address, '', :required => false %>
  </div>
  <div>
  <%= 'Select your 5th row'%>
    <%= select_tag "credit_card", options_for_select([ "name", "birthday", "phone", "address", "credit_card", "email" ], "credit_card"), :required => true %>
  <%= label_tag 'or your own field'%>
    <%= text_field_tag :credit_card, '', :required => false %>
  </div>
  <div>
  <%= 'Select your 6th row'%>
    <%= select_tag "email", options_for_select([ "name", "birthday", "phone", "address", "credit_card", "email" ], "email"), :required => true %>
    <%= label_tag 'or your own field'%>
    <%= text_field_tag :email, '', :required => false %>
  </div>
  <div>
  <%= submit_tag "Import Contacts", class: 'btn2' %>
  </div>
<% end %>
</div>

app/views/import_contacts/index.html.erb
<h2>Uploaded Files</h2>

<div class="container">
<h4>Do you have upload contacts?</h4>
<%= link_to 'Next to upload', new_import_contact_path, class: 'btn1' %>
</div>

<div class="row m-0">
  <table class="table">
  <tr>
    <th>Filename</th>
    <th>State</th>
  </tr>

  <% @imported_contacts.each do |imported_contact| %>
    <tr>
      <td><%= imported_contact.filename %></td>
      <td><%= imported_contact.state %></td>
      
    </tr>
  <% end %>
  </table>
</div>

<%= will_paginate @imported_contacts %>

app/views/import_contacts/new.html.erb
<div class="container">
<h2>Import CSV Files</h2>


<%= render 'form', import_contact: @import_contact %>
</div>